import SEO from "@/components/SEO";
import PageScaffold from "@/components/layout/PageScaffold";
import {
  buildBreadcrumbSchema,
  buildWebPageSchema,
  organizationSchema,
} from "@/lib/seo";

export default function PrivacyPolicyPage() {
  const description =
    "Review the MydropAI privacy policy to understand how we collect, process, and protect your data.";

  const structuredData = [
    organizationSchema,
    buildWebPageSchema("MydropAI Privacy Policy", "/privacy-policy", description),
    buildBreadcrumbSchema([
      { name: "Home", path: "/" },
      { name: "Privacy Policy", path: "/privacy-policy" },
    ]),
  ];

  return (
    <>
      <SEO
        title="Privacy Policy"
        description={description}
        canonicalUrl="/privacy-policy"
        structuredData={structuredData}
      />
      <PageScaffold
        title="Privacy Policy"
        description="This page describes how we collect, use, share, and protect your information when you use MydropAI."
      >
        <article className="prose prose-invert mx-auto mt-12 mb-20 max-w-4xl space-y-8 text-slate-200">
          <section>
            <h2>1. Overview</h2>
            <p>
              Your privacy is a priority. This policy explains what information we collect when you use our services, why we collect it, how it is used, and what rights you have. The goal is to be transparent and help you make informed decisions about your data.
            </p>
            <p>
              We follow applicable privacy laws in markets where we operate, including GDPR, CCPA, and similar regulations. We do not sell your personal data in exchange for money, and we minimize data collection to only what is necessary to deliver our service.
            </p>
            <p>
              The service names “Mydrop” and “Mydrop AI” are trade names used by ADB International LLC, a United States limited liability company. References to “we”, “us”, and “our” in this policy refer to ADB International LLC.
            </p>
          </section>

          <section>
            <h2>2. Information We Collect</h2>
            <p>
              We collect information you provide directly, information generated by your use of the services, and information from third parties when authorized. We keep data categories broad to avoid exposing internal implementation details.
            </p>
            <h3>2.1. Account Information</h3>
            <ul>
              <li>Email address and profile name</li>
              <li>Account settings and preferences</li>
              <li>Consent choices and communications preferences</li>
            </ul>
            <h3>2.2. Usage Information</h3>
            <ul>
              <li>Actions you take in the service (e.g., creating, editing, scheduling content)</li>
              <li>Performance, errors, and interaction metrics</li>
              <li>Log records, device identifiers, and timestamps</li>
            </ul>
            <h3>2.3. Technical Information</h3>
            <ul>
              <li>IP address and geolocation at a city level</li>
              <li>Browser, operating system, and device type</li>
              <li>Network details for security and fraud prevention</li>
            </ul>
            <h3>2.4. Marketing and Attribution Information</h3>
            <ul>
              <li>Referral source, campaign tags, and tracking identifiers</li>
              <li>Engagement with marketing messages and promotional offers</li>
            </ul>
          </section>

          <section>
            <h2>3. How We Use Information</h2>
            <p>
              We use collected information to provide, support, and improve the service, to communicate with you, and to meet our legal obligations.
            </p>
            <h3>3.1. Service Delivery</h3>
            <ul>
              <li>Create and manage your account</li>
              <li>Process requests and actions initiated by you</li>
              <li>Manage subscriptions and transactions</li>
            </ul>
            <h3>3.2. Personalization and Improvement</h3>
            <ul>
              <li>Tailor the user experience to your preferences</li>
              <li>Develop and test new features</li>
              <li>Perform internal analytics and product evaluation</li>
            </ul>
            <h3>3.3. Communication</h3>
            <ul>
              <li>Send account-related notices and updates</li>
              <li>Provide customer support and respond to inquiries</li>
              <li>Deliver optional marketing newsletters when permitted</li>
            </ul>
            <h3>3.4. Legal, Security, and Compliance</h3>
            <ul>
              <li>Prevent abuse, spam, fraud, and security incidents</li>
              <li>Investigate potential violations and enforce terms</li>
              <li>Comply with legal requests and court orders</li>
            </ul>
          </section>

          <section>
            <h2>4. Sharing and Disclosure</h2>
            <p>
              We do not sell or trade personal information. We may share personal data in controlled circumstances with third parties who support our operations or when required by law.
            </p>
            <h3>4.1. Service Providers</h3>
            <p>
              We work with trusted providers for infrastructure hosting, authentication, communication, billing, and analytics. These vendors act on our instruction and are bound by contract to protect your information.
            </p>
            <h3>4.2. Third-Party Integrations</h3>
            <p>
              You may choose to connect external services. Information shared with connected providers depends on what you authorize. We encourage you to review those providers’ privacy policies.
            </p>
            <h3>4.3. Legal Obligations</h3>
            <p>
              We may disclose information when required by law, regulation, or legal process, or to respond to lawful requests from public authorities.
            </p>
          </section>

          <section>
            <h2>5. Cookies and Similar Technologies</h2>
            <p>
              We and our partners use cookies, web beacons, local storage, and similar technologies. These tools help secure your account, maintain your session, and understand service usage.
            </p>
            <h3>5.1. Essential Cookies</h3>
            <p>
              Necessary for core functionality like authenticating your session and keeping you logged in.
            </p>
            <h3>5.2. Analytics Cookies</h3>
            <p>
              Used to collect aggregated usage data for improvement and troubleshooting. This data is often anonymized.
            </p>
            <h3>5.3. Advertising and Attribution</h3>
            <p>
              Used to measure the effectiveness of our campaigns and provide relevant offers. These are controlled by your preferences when available.
            </p>
            <p>
              You can manage or disable cookies through your browser settings, but doing so may affect how the service functions.
            </p>
          </section>

          <section>
            <h2>6. Data Retention and Deletion</h2>
            <p>
              We retain data only as long as needed to provide services and meet legal requirements. When you request deletion, we initiate a process to remove your information from active systems.
            </p>
            <h3>6.1. Active Account Retention</h3>
            <p>
              Personal and usage data is kept while your account is active and as necessary for legitimate business purposes, such as providing customer support and improving services.
            </p>
            <h3>6.2. Account Closure</h3>
            <p>
              Upon request, we delete account data from primary systems within a reasonable period. Some data may remain in backups for a limited time, as required by law or for security purposes.
            </p>
            <h3>6.3. Legal Hold</h3>
            <p>
              If required by law, data may be retained longer even after account deletion, until the legal hold is released.
            </p>
          </section>

          <section>
            <h2>7. Your Rights and Choices</h2>
            <p>
              You may have rights to access, correct, delete, or export your personal data. You may also object to certain processing, including targeted marketing, where applicable.
            </p>
            <h3>7.1. Access and Correction</h3>
            <p>
              You can review and update your profile information in account settings. Contact us for support if you need assistance.
            </p>
            <h3>7.2. Data Portability</h3>
            <p>
              When applicable, we provide a way to export your data in a structured format.
            </p>
            <h3>7.3. Deletion</h3>
            <p>
              You can request deletion through the account settings or by contacting us. We will respond promptly to the extent required by law.
            </p>
            <h3>7.4. Cookies and Tracking Preferences</h3>
            <p>
              You can withdraw consent for optional tracking at any time through your cookie preferences or browser controls.
            </p>
          </section>

          <section>
            <h2>8. Security</h2>
            <p>
              We employ industry-standard safeguards to protect your data, including encryption in transit and at rest, access controls, monitoring, and periodic security reviews.
            </p>
            <h3>8.1. Access Controls</h3>
            <p>
              Access to personal information is limited to authorized personnel who need it for legitimate business purposes.
            </p>
            <h3>8.2. Incident Response</h3>
            <p>
              We maintain an incident response program and will notify affected users as required by law if we detect a security breach.
            </p>
          </section>

          <section>
            <h2>9. International Data Transfers</h2>
            <p>
              Your data may be processed in multiple jurisdictions. We use appropriate safeguards, such as standard contractual clauses or equivalent protections, to ensure data is handled securely across borders.
            </p>
          </section>

          <section>
            <h2>10. Children’s Privacy</h2>
            <p>
              This service is intended for users aged 16 and older. We do not knowingly collect information from children under the age limit. If we learn that a child has provided us with personal data, we will take steps to delete it.
            </p>
          </section>

          <section>
            <h2>11. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy periodically. The policy will indicate the last updated date. If changes are material, we will provide notice via email or in-app notification.
            </p>
            <p>
              Effective date: April 1, 2026. Last updated: April 1, 2026.
            </p>
          </section>

          <section>
            <h2>12. Contact Information</h2>
            <p>
              If you have questions about our privacy practices, to exercise your rights, or to make a complaint, reach out to us at <a href="mailto:contact@mydropai.com" className="text-primary">contact@mydropai.com</a>.
            </p>
            <p>
              You may also contact a data protection authority in your jurisdiction if you are not satisfied with our response.
            </p>
          </section>
        </article>
      </PageScaffold>
    </>
  );
}
